### ISSUE TITLE
Unable to install: requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by dima-ag** [nunomaduro/larastan#1977] opened 2024-06-21 10:48 UTC
- Larastan Version: ^2.0
- Laravel Version: 11.11.1

### Description
I run `composer require larastan/larastan:^2.0 --dev` and I get the following output in my terminal, and installation aborts.
```console
λ composer require larastan/larastan:^2.0 --dev
The "2.0" constraint for "larastan/larastan" appears too strict and will likely not match what you want. See https://getcomposer.org/constraints
./composer.json has been updated
Running composer update larastan/larastan
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires larastan/larastan 2.0 -> satisfiable by larastan/larastan[2.0.0].
    - larastan/larastan 2.0.0 requires illuminate/console ^9 -> found illuminate/console[v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
```

**Comment by szepeviktor** [comment] 2024-06-21 11:08
Hello @dima-ag 👋🏻
You must be on Windows.

Duplicate of #1971

**Closed as not planned by szepeviktor** 2024-06-21 11:08 UTC
Labels: bug
