### ISSUE TITLE
Crypt::decrypt and No application encryption key has been specified.

### ISSUE THREAD

**Issue by arxeiss** [nunomaduro/larastan#753] opened 2021-01-06 08:30 UTC
- Larastan Version: 0.6.11
- `--level` used: 6

### Description

In one controller I have this piece of code:

```php
$folder = Crypt::decrypt($request->input('f'))
```
If I run phpstan on my local machine, it works. But if I run it in Gitlab CI I'm getting error below. This was not happening in previous versions of Larastan. If I remove `.env` file locally, I got the same error on my machine.

I know what is the problem, missing app key, but I don't know why I should need that for static analysis. And in previous versions it wasn't needed. I updated from `0.6.10` to `0.6.11`.

```
 Illuminate\Encryption\MissingAppKeyException 

  No application encryption key has been specified.

  at vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79
     75▕     protected function key(array $config)
     76▕     {
     77▕         return tap($config['key'], function ($key) {
     78▕             if (empty($key)) {
  ➜  79▕                 throw new MissingAppKeyException;
     80▕             }
     81▕         });
     82▕     }
     83▕ }

```

**Comment by szepeviktor** [comment] 2021-01-06 09:36
Duplicate of #752

**Closed by szepeviktor** 2021-01-06 09:36 UTC
