### ISSUE TITLE
Unresolvable "expects non-empty-string, string given" errors

### ISSUE THREAD

**Issue by LastDragon-ru** [nunomaduro/larastan#1011] opened 2021-11-06 08:06 UTC
- Larastan Version: 1.0.0
- `--level` used: 8

### Description

Some off setters accepts only a `non-empty-string` since 1.0, but getters still return `string` => so there are a lot of "expects non-empty-string, string given" :(

Moreover, I'm not sure how to solve:

```php
// class TestObject extends Model
$key = (new TestObject())->getKeyName();
$all = TestObject::query()->reorder($key)->get()->all();
```

that gives:
```
 31     Parameter #1 $column of method Illuminate\Database\Eloquent\Builder<LastDragon_ru\LaraASP\Eloquent\Testing\Package\Models\TestObject>::reorder() expects non-empty-string|null, string given.
```

In the theory `getKeyName()` can return an empty string, but adding a check on every usage looks too boring. 

Maybe there is another way? (except baseline)

**Comment by szepeviktor** [comment] 2021-11-06 08:18
Hello @LastDragon-ru!

Yes there is.

Duplicate of https://github.com/nunomaduro/larastan/issues/1009#issuecomment-961662594

**Closed by szepeviktor** 2021-11-06 08:18 UTC
