### ISSUE TITLE
Does Larastan support automatic {relation}_count property?

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#1370] opened 2022-09-08 19:01 UTC
Docs: https://laravel.com/docs/9.x/eloquent-relationships#counting-related-models

I see code like `$model->players_count` causing `Access to an undefined property`.
`Model::players()` method does exists.

**Comment by markuskooche** [comment] 2022-09-14 12:22
You can fix this by setting a property in the PHPDocs.

```
class User extends Authenticatable
{
    public function followers(): HasMany
    {
        // ...
    }
}
```

For example in a resource:
```
/**
 * @mixin User
 *
 * @property int $followers_count
 */
class UserResource extends JsonResource
{
    public function toArray($request): array
    {
        return [
            'followers_count' => $this->followers_count,
        ];
    }
}
```

**Comment by canvural** [comment] 2022-10-12 09:16
Duplicate of #466

**Closed by canvural** 2022-10-12 09:16 UTC
