### ISSUE TITLE
Internal error on Lumen: "Call to undefined function NunoMaduro\Larastan\ReturnTypes\now()"

### ISSUE THREAD

**Issue by halloei** [nunomaduro/larastan#1446] opened 2022-11-15 12:13 UTC
- Larastan Version: 2.2.9
- `--level` used: 5
- Pull request with failing test: % 

### Description
When using Lumen with facades enabled, I get a `Internal error: Internal error: Call to undefined function NunoMaduro\Larastan\ReturnTypes\now()` error when using `\Illuminate\Support\Facades\Date::now()`.
The bug was introduced in Larastan version 2.1.5.

### Laravel code where the issue was found
I created a [fresh Lumen project](https://github.com/halloei/larastan-issue-2022-11-15) and committed without changes. All changes that are needed to reproduce the error are included in the [second commit](https://github.com/halloei/larastan-issue-2022-11-15/commit/2d4e27759c1038a693e382ce0b9a23ed022394fd).

**Comment by mad-briller** [comment] 2022-11-15 12:54
will be caused by the usage of `now()` on this line:
https://github.com/nunomaduro/larastan/blob/master/src/ReturnTypes/DateExtension.php#L44

presumably Luman doesn't have the `now()` helper present so the code crashes, it could be changed to use `Date::now()` instead but that could have the same issue if not using facades

with Lumen no longer being [officially supported for new projects](https://lumen.laravel.com/docs/9.x#installation), its on @canvural to decide whether Larastan supports Lumen going forwards, and as such whether this will be fixed

**Comment by canvural** [comment] 2022-12-29 11:04
Lumen is not supported. So there is no plan to make this work in Lumen.

**Closed by canvural** 2022-12-29 11:04 UTC
