### ISSUE TITLE
JsonResource::make() expects Illuminate\Http\Resources\Json\dynamic

### ISSUE THREAD

**Issue by brendt** [nunomaduro/larastan#27] opened 2018-07-18 13:16 UTC
```
Parameter #1 ...$parameters of static method Illuminate\Http\Resources\Json\JsonResource::make() expects Illuminate\Http\Resources\Json\dynamic, App\Domain\Template\Models\Template given
```

**Comment by nunomaduro** [comment] 2018-07-24 22:14
Duplicate of #15.

**Closed by nunomaduro** 2018-07-24 22:14 UTC
Labels: false positive
