### ISSUE TITLE
Larastan doesn't detect a renameColumn name

### ISSUE THREAD

**Issue by rudiedirkx** [nunomaduro/larastan#1919] opened 2024-04-16 14:09 UTC
- Larastan Version: v2.9.4
- Laravel Version: v10.48.7
- Level: 1

### Description

In a migration, I create a column `last_changed_at`, and in a later migration I do a `$table->renameColumn('last_changed_at', 'first_detection_at')`. `last_changed_at` isn't used anymore, but `first_detection_at` is.

But phpstan gives me an error:

> Access to an undefined property App\Models\SiteCheck::$first_detection_at.

Only that property. All the others are detected OK. It seems the `renameColumn()` doesn't work.

If I edit the migration and add in `up()`:

```php
// larastan
return;
\Schema::table('site_checks', function(Blueprint $table) {
	$table->timestamp('first_detection_at');
});
```

Larastan gets it. But that's too hacky, even for me.

If I add some debug in `SchemaAggregator`:

```php
case 'renamecolumn':
	dump($columnName, $secondArg->value);
```

and run phpstan with `--debug`, it seems Larastan does understand the renameColumn():

```
"last_changed_at" // vendor/larastan/larastan/src/Properties/SchemaAggregator.php:412
"first_detection_at" // vendor/larastan/larastan/src/Properties/SchemaAggregator.php:412
```

but it still doesn't apply the change...?

Should I read the migrations as bootstrap files or something?

<s>I'll try to upgrade Laravel and Larastan to try the newest version.</s> Same error with newest versions.

**Comment by rudiedirkx** [comment] 2024-04-16 14:15
I upgraded Larastan to v2.9.4, and Laravel to v10.48.7, and I get the same error, and the same debug.

Just different line numbers:

```
"last_changed_at" // vendor/larastan/larastan/src/Properties/SchemaAggregator.php:628
"first_detection_at" // vendor/larastan/larastan/src/Properties/SchemaAggregator.php:628
```

**Comment by calebdw** [comment] 2024-04-16 14:29
Everything is working as expected: #1920

**Comment by rudiedirkx** [comment] 2024-04-16 14:41
As in, what I see happening isn't happening? Or, you can't reproduce it? New unit tests don't change my reality... If it doesn't work for me, it might not work for others, despite your passing unit tests.

**Comment by canvural** [comment] 2024-04-16 14:43
Hi,

We'd need more information. Or even better a small repository that can reproduce the issue. As you can see, we cannot reproduce it.

**Comment by calebdw** [comment] 2024-04-16 14:43
Without seeing your migration or a MRE there's not much we can do to help...

**Comment by rudiedirkx** [comment] 2024-04-16 18:14
Crap. https://github.com/rudiedirkx/larastan-demo works fine, and I can't break it. Pretty realistic. Property used in the model. Up 
and down migration with renameColumn, with some raw SQL statements, and `\Schema` instead of using the facade class. In both projects I only test `app/`, not `database/migrations/`.

Debug does the same, but in this case it works... I don't get it.

**Comment by canvural** [comment] 2024-04-16 18:17
Closing then. Feel free to open a new one or comment here if you manage to reproduce it in the repository.

**Closed as not planned by canvural** 2024-04-16 18:17 UTC
Labels: bug

**Comment by calebdw** [comment] 2024-04-16 18:18
Try to clear the phpstan cache

**Comment by rudiedirkx** [comment] 2024-04-16 18:25
> Try to clear the phpstan cache

I do that often. And in this case in run with `--debug`, so no cache.

Is there a way to debug model properties? Or do they only resolve during analysis? I don't understand how larastan sees and evals the renameColumn, but still doesn't know the new property. Can I see a list of properties it finds or something?

**Comment by calebdw** [comment] 2024-04-16 18:26
Maybe you have a misspelling somewhere?

**Comment by canvural** [comment] 2024-04-16 18:33
> > Try to clear the phpstan cache
> 
> I do that often. And in this case in run with `--debug`, so no cache.
> 
> Is there a way to debug model properties? Or do they only resolve during analysis? I don't understand how larastan sees and evals the renameColumn, but still doesn't know the new property. Can I see a list of properties it finds or something?

After [this line](https://github.com/larastan/larastan/blob/5bc58cc6d3a3e5f728efadeda08116192dc9fa92/src/Properties/ModelPropertyHelper.php#L218) you can put a `dd($this->tables)` to see everything Larastan recognized.

**Comment by rudiedirkx** [comment] 2024-04-16 18:34
It doesn't know the old column name either (which is good), so it REALLY seems like Larastan understands the column name change! 😮 but not really...

The new column `first_detection_at` is used in more places, and they all work (no "undefined property" errors), except the `$this` one in the model.

Model method test:

```php
public function getLastChangedDifference() {
	var_dump($this->last_changed_at);
	var_dump($this->first_detection_at);

	$foo = self::find(123);
	var_dump($foo->last_changed_at);
	var_dump($foo->first_detection_at);
}
```

Both of the `$this` properties are "undefined property" errors, and neither of the `$foo`.

**Comment by rudiedirkx** [comment] 2024-04-16 18:44
> After [this line](https://github.com/larastan/larastan/blob/5bc58cc6d3a3e5f728efadeda08116192dc9fa92/src/Properties/ModelPropertyHelper.php#L218) you can put a `dd($this->tables)` to see everything Larastan recognized.

There's no `first_detection_at` column! Yet, in other places (outside `$this` context), there's no error for this property, so sometimes it does exist..... Computers are weird.

```
                        case 'dropcolumn':
                        case 'dropifexists':
                        case 'dropsoftdeletes':
                        case 'dropsoftdeletestz':
                        case 'removecolumn':
                        case 'drop':
dump($columnName);
```

never triggers for `first_detection_at`, so it doesn't think it's deleted after being renamed.

I give up.

**Comment by rudiedirkx** [comment] 2024-04-16 18:49
Waaaaaaaaaaaaaaaait!!

```
"UNRENAMABLE: last_changed_at" // vendor/larastan/larastan/src/Properties/SchemaTable.php:31
```

```php
    public function renameColumn(string $oldName, string $newName): void
    {
        if (! isset($this->columns[$oldName])) {
dump("UNRENAMABLE: $oldName");
            return;
        }

```

Larastan doesn't even think the original column `last_changed_at` exists. And that totally makes sense, because I'm an idiot!

An earlier migration created `last_changed_at`, but not using Schema/Blueprint:

```
		\DB::statement("
			alter table site_checks
			drop started_at,
			change finished_at last_changed_at int unsigned not null,
			add remote int unsigned not null default 0
		");
```

Sorry for wasting your time guys. That was not mysterious at all.

Maybe `SchemaTable::renameColumn()` could throw a warning or something 😆 so dumb people don't get confused for days.

Thanks for bearing with me. I'll make better migrations in the future ❤️

**Comment by rudiedirkx** [comment] 2024-04-16 18:50
This is still really weird though:

> Yet, in other places (outside `$this` context), there's no error for this property, so sometimes it does exist.....

Is that the level? Why does phpstan sometimes NOT complain about unknown property `first_detection_at`??

**Comment by rudiedirkx** [comment] 2024-04-16 18:53
> Is that the level?

Yes, level 1 doesn't complain. Level 2 does. Alright, I'm really done here now 😆 Thanks guys.
