### ISSUE TITLE
The string-in DataTime-out is not supported.

### ISSUE THREAD

**Issue by anubhav217** [nunomaduro/larastan#905] opened 2021-07-27 18:46 UTC
- Larastan Version: #.#.#
- `--level` used:
- Pull request with failing test:

### Laravel code where the issue was found

```php

```

**Comment by szepeviktor** [comment] 2021-07-27 18:50
Duplicate of #902

Please do not open spam issues.

**Closed by szepeviktor** 2021-07-27 18:50 UTC
