### ISSUE TITLE
Calling get on Model::newQuery returns generic Model type

### ISSUE THREAD

**Issue by wslawski-printify** [nunomaduro/larastan#1683] opened 2023-07-05 13:22 UTC
- Larastan Version: 2.6.3
- `--level` used: 8

### Description

When having model assigned to property and then when getting result from `newQuery` it returns for example collection with generic model type, instead of expected one.

### Laravel code where the issue was found

```php
class CSVOrderImportProcessRepository
{
    private CSVOrderImportProcess $model;

    public function __construct()
    {
        $this->model = new CSVOrderImportProcess();
    }

    /** @return Collection<int, CSVOrderImportProcess> */
    public function getByShop(int $shopId): Collection
    {
        return $this->model->setConnection(SecondaryConnection::NEAREST_CONNECTION_NAME)->newQuery()
            ->where(CSVOrderImportProcess::SHOP_ID, $shopId)
            ->get();
    }
}
```

Here I am getting error like:

```                                        
 ------ ------------------------------------------------------------------------------------------------------ 
  26     Method App\DIS\Models\Mongo\CSVOrderImportProcessRepository::getByShop() should return                
         Illuminate\Database\Eloquent\Collection<int, App\DIS\Models\Mongo\CSVOrderImportProcess> but returns  
         Illuminate\Database\Eloquent\Collection<int, Illuminate\Database\Eloquent\Model>. 
 ```

What I expect - no error

**Comment by szepeviktor** [comment] 2023-07-05 13:33
Thank you for your report.

What is the return type of setConnection?
```php
\PHPStan\dumpType($this->model->setConnection(SecondaryConnection::NEAREST_CONNECTION_NAME));
```

**Comment by wslawski-printify** [comment] 2023-07-10 10:12
```
\PHPStan\dumpType($this->model->setConnection(SecondaryConnection::NEAREST_CONNECTION_NAME));
Dumped type: App\DIS\Models\Mongo\CSVOrderImportProcess
\PHPStan\dumpType($this->model->setConnection(SecondaryConnection::NEAREST_CONNECTION_NAME)->newQuery())
Dumped type: Illuminate\Database\Eloquent\Builder
```

**Comment by canvural** [comment] 2023-07-16 17:50
Looks like the issue is with `setConnection` if anyone wants to investigate.

**Comment by sanfair** [comment] 2023-07-25 10:21
@wslawski-printify Can't reproduce your issue. 

Can you check https://github.com/sanfair/larastan-playground/pull/3 and point out what I'm missing here?

PHPStan did not found any issues here https://github.com/sanfair/larastan-playground/actions/runs/5655529029

**Comment by canvural** [comment] 2023-07-30 09:54
Thank you @sanfair for the reproduction. Closing this as we can't reproduce it. Please open a new issue with more information if this continues to happen.

**Closed by canvural** 2023-07-30 09:54 UTC
Labels: bug
