### ISSUE TITLE
View macros giving undefined method error in 2.3.x

### ISSUE THREAD

**Issue by rovansteen** [nunomaduro/larastan#1493] opened 2022-12-26 09:48 UTC
- Larastan Version: 2.3.1
- `--level` used: 6
- Pull request with failing test: N/A

### Description
Trying to upgrade to `2.3.x` it seems like view macros (like Livewire) no longer work together with larastan. I guess this is because `view()` now resolves to the contract and no longer the actual implementation in Laravel where the macros are being registered.

### Laravel code where the issue was found

```php
view(...)->layout(...)
```
Gives
`Call to an undefined method Illuminate\Contracts\View\View::layout().`

**Comment by szepeviktor** [comment] 2022-12-26 11:52
Thank you @rovansteen! 👋🏻 

Could it be the duplicate of  #1490?

**Comment by canvural** [comment] 2022-12-27 09:40
Duplicate of #1490

**Closed by canvural** 2022-12-27 09:40 UTC

**Comment by rovansteen** [comment] 2022-12-27 15:23
Thanks for the quick fix @canvural!
