### ISSUE TITLE
Environment() invoked with 1 parameter, 0 required.

### ISSUE THREAD

**Issue by mauricehofman** [nunomaduro/larastan#184] opened 2018-10-25 19:34 UTC
- Larastan Version: 0.3.4
- `--level` used: default

### Description:
` Method Illuminate\Contracts\Foundation\Application::environment() invoked with 1 parameter, 0 required.  `

### Laravel code where the issue was found:
`$this->app->environment('local')` will trigger this error because this function uses `func_num_args` and `func_get_args`

**Comment by szepeviktor** [comment] 2018-10-25 19:47
@mauricehofman You are welcome to send a PR.
It is very easy!

**Comment by claystation** [comment] 2019-02-19 08:44
I tried adding a test for this using the following:

```
<?php

declare(strict_types=1);

namespace Tests\Features\Methods;

use Illuminate\Foundation\Application;

class ApplicationExtension
{
    /**
     * @return bool|string
     */
    public function testApplicationEnvironment()
    {
        $app = new Application;
        return $app->environment('production');
    }
}
```

This gives me no errors when running the tests. Although it gives me errors while using it in my own Laravel app. Also, if i replace `environment('production')` with `isLocal('production')`. `isLocal()` does not take any arguments either and is also not supposed to so it should fail. And it does fail with the same error. Am i writing the test horribly wrong or is this already fixed in master but not released yet?

**Comment by spawnia** [comment] 2019-08-14 06:38
@nunomaduro this is a duplicate of #91

**Comment by szepeviktor** [comment] 2019-08-14 06:45
Yes.
Than you.

**Closed by szepeviktor** 2019-08-14 06:45 UTC
Labels: false positive
