### ISSUE TITLE
Access to an undefined property 

### ISSUE THREAD

**Issue by wrabit** [nunomaduro/larastan#583] opened 2020-05-22 11:45 UTC
Latest laravel and default settings

Many reports of "Access to an undefined property Illuminate\Database\Eloquent\Model::$attribute."

**Comment by canvural** [comment] 2020-05-22 11:48
Hi,

Can you share any code sample where this error happens? Also please follow the [issue template](https://github.com/nunomaduro/larastan/blob/master/.github/ISSUE_TEMPLATE.md) for new issues.

**Comment by szepeviktor** [comment] 2020-05-22 11:55
This would make it possible for us to help you.

**Comment by wrabit** [comment] 2020-05-22 12:06
I'm seeing it about all of my resources and their fields (which are standard) i.e.

```
Access to an undefined property App\Http\Resources\UserResource::$first_name.

----

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class UserResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'first_name'     => $this->first_name,
            ...
```


```
Providers/RouteServiceProvider.php
  101    Access to an undefined property Illuminate\Foundation\Application::$request.
  157    Access to an undefined property Illuminate\Foundation\Application::$request.
  164    Access to an undefined property Illuminate\Foundation\Application::$request.

----

        Route::bind('risks', function($value, \Illuminate\Routing\Route $route) {
            $dpia = app()->request->route('dpias');
            ...
```

A lot of my traits:

```
Line   Traits/MorphsToManySecurityMeasures.php (in context of class App\Models\Org\System)
Access to an undefined property Illuminate\Database\Eloquent\Model::$id.

----

    public static function bootMorphsToManySecurityMeasures()
    {
        static::deleted(function(Model $model) {
            \DB::table('security_measurables')
                ->where('security_measurable_type', $model->getMorphClass())
                ->where('security_measurable_id', $model->id)
                ->delete();
        });
    }
```

**Comment by szepeviktor** [comment] 2020-05-22 12:14
Thank you for your _complete_ report!

To me these seem to be three slightly different issues.

**Comment by wrabit** [comment] 2020-05-22 12:17
@szepeviktor thanks for your _helpful_ comments!

**Comment by Daanra** [comment] 2020-05-22 13:23
The first problem can be solved by adding the following PHPDoc annotation to your resource class:
```php
/** @extends JsonResource<User> */
```
as [described here](https://github.com/nunomaduro/larastan/blob/master/UPGRADE.md#eloquent-resources).



The second problem can be resolved by changing it to either
```php
$dpia = request()->route('dpias');
```
or
```php
$dpia = app('request')->route('dpias');
```


The last problem is expected behavior, because `Model` does not have an `id` by definition. You can either ignore it by adding e.g. `// @phpstan-ignore-next-line`, or you could create a custom Model class:
```php
/** 
 * @property int $id
 */
class MyCustomModel extends Model {}
```
and use that as a typehint.

**Closed** 2020-05-22 14:35 UTC

**Comment by Scuissiatto** [comment] 2022-01-13 18:16
For those who were looking to solve this problem please refer to this https://github.com/nunomaduro/larastan/commit/37f9ce80890a67a02b1d55bf79eb73604880c6b9

**Comment by nickescobedo** [comment] 2022-02-25 05:09
If you don't feel like clicking the link the latest way to fix this is to add @mixin above the class name in the doc block.
For example if it's a User resource.

`@mixin \App\User`

**Comment by zabocado** [comment] 2022-05-06 01:49
> If you don't feel like clicking the link the latest way to fix this is to add `@mixin` above the class name in the doc block. For example if it's a `User` resource.
> 
> `@mixin \App\User`

Remember to use a docblock comment
 `/** @mixin \App\User **/` - CORRECT

and not 
 `/* @mixin \App\User */` - WRONG

otherwise it won't work.

**Comment by szepeviktor** [comment] 2022-05-06 01:51
You can improve your doc-blocks: `/** @mixin \App\User */`

**Comment by zabocado** [comment] 2022-05-06 02:02
> You can improve your doc-blocks: `/** @mixin \App\User */`

It feels wrong, without the symmetry.

**Comment by apoca** [comment] 2022-07-25 19:56
well, I have the same issue and I am using the annotation:

` PHPDoc tag @extends contains generic type Illuminate\Http\Resources\Json\JsonResource<App\Models\ProjectPublicCommentImage> but class Illuminate\Http\Resources\Json\JsonResource is not generic.  `

Can someone clarify if I am doing something wrong?

**Comment by nickescobedo** [comment] 2022-07-25 20:01
> 

You need to use @mixin not @extends.

**Comment by apoca** [comment] 2022-07-26 16:34
One more... I have this piece of code:

`/**
     * @var \Illuminate\Contracts\Auth\Authenticatable|\App\Models\User|null
     */
    protected Authenticatable|null|User $authUser;

    /**
     * @param ProjectPublicCommentManager $projectPublicCommentManager
     */
    public function __construct(
        ProjectPublicCommentManager $projectPublicCommentManager
    ) {
        $this->projectPublicCommentManager = $projectPublicCommentManager;
        $this->authUser = Auth::user();
    }`

And I am getting a similar issue:

`Access to an undefined property                      
         Illuminate\Contracts\Auth\Authenticatable::$id. ` 

In this case what i should do?

**Comment by szepeviktor** [comment] 2022-07-26 18:55
@apoca Please search issues for "Authenticatable"
https://github.com/nunomaduro/larastan/issues/836#issuecomment-848637431 👀

**Comment by tbuteler** [comment] 2022-12-29 16:15
For those using `@mixin` on your Laravel API resources and still getting "Access to an undefined property", the model itself is likely at fault, see #1468 (i.e. Larastan uses migration files to understand which attributes are valid to a given model).
