### ISSUE TITLE
HasManyThrough relation getQuery() return type loses model generic

### ISSUE THREAD

**Issue by rudiedirkx** [nunomaduro/larastan#2069] opened 2024-10-13 14:51 UTC
- Larastan Version: v2.9.8
- Laravel Version: v11.23.5

### Description

Phpstan understands the type of a model's relation query, but after `getQuery()` it loses the specific model/generic.

### Laravel code where the issue was found

```php
\PHPStan\dumpType($organization); // 🟩 App\Models\Organization
\PHPStan\dumpType($organization->site_checks()); // 🟩 Illuminate\Database\Eloquent\Relations\HasManyThrough<App\Models\SiteCheck>
\PHPStan\dumpType($organization->site_checks()->getQuery()); // 🟥 Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>
```

In the last dump, the model becomes an eloquent model instead of `SiteCheck`. Which is weird, because `getQuery()` in Laravel does have a return hint:

    @return \Illuminate\Database\Eloquent\Builder<TRelatedModel>

and it still knew `TRelatedModel` the dump before.

I don't get it. I don't even know who's doing it wrong. Me, Larastan, Phpstan, or Laravel?

**Comment by rudiedirkx** [comment] 2024-10-13 14:55
Eeeeh it's probably me, because somewhere else:

```
\PHPStan\dumpType($this->organization->sites()->getQuery()); // 🟩 Illuminate\Database\Eloquent\Builder<App\Models\Site>
```

It still knows about `Site`.

Maybe because my `SiteCheck` is also a generic, and my `Organization::site_checks()` doesn't specify that (because it doesn't know the specific):

```php
// No @return here
public function site_checks() : Relations\HasManyThrough {
	return $this->hasManyThrough(SiteCheck::class, Site::class, 'organization_id', 'site_id');
}
```

**Comment by rudiedirkx** [comment] 2024-10-13 14:59
But if I add a `@return` with the generic (`Checked` is still generic, because no idea which type it returns):

```php
/** @return Relations\HasManyThrough<SiteCheck<Checked>> */
public function site_checks() : Relations\HasManyThrough {
	return $this->hasManyThrough(SiteCheck::class, Site::class, 'organization_id', 'site_id');
}
```

phpstan complains about its return value:

> Method `Organization::site_checks()` should return `Relations\HasManyThrough<SiteCheck<Checked>>` but returns `Relations\HasManyThrough<SiteCheck>`.

because yeah kinda, because `hasManyThrough()` doesn't know about a potential generic. Is that Larastan's fault, because it doesn't take potential generics into account? How do I fix this?

**Comment by rudiedirkx** [comment] 2024-10-13 15:03
And with that `@return` the original problem holds: `getQuery()` loses the generic type `SiteCheck`.

**Comment by rudiedirkx** [comment] 2024-10-13 15:06
Wow, generics are a lot of trouble with phpstan level 5+. Suddenly `argument.type` errors everywhere. Like these:

> Parameter `#1` $query of static method `Watchlist::getChecks()` expects `Builder<SiteCheck<Checked>>`, `Builder<SiteCheck>` given.

Come ooon! That's good enough!

**Comment by calebdw** [comment] 2024-10-14 13:24
Use the wildcard if you're not sure / don't care what the inner types will be:

```php
/** @return Relations\HasManyThrough<SiteCheck<*>> */
public function site_checks() : Relations\HasManyThrough {
	return $this->hasManyThrough(SiteCheck::class, Site::class, 'organization_id', 'site_id');
}
```

**Comment by rudiedirkx** [comment] 2024-10-14 13:45
That's good to know, but that doesn't solve any part of the problem. `getQuery()` still returns `EloquentBuilder<EloquentModel>` instead of `EloquentBuilder<SiteCheck>` (or even with generic: `EloquentBuilder<SiteCheck<*>>`). I **think** Larastan doesn't support generics in relationship return types. That's why `sites()` works (`Site` is not a generic), but `site_checks()` doesn't (`SiteCheck` is a generic). I **think**. The `@return` in

```php
/** @return Relations\HasManyThrough<SiteCheck<*>> */
public function site_checks() : Relations\HasManyThrough {
	return $this->hasManyThrough(SiteCheck::class, Site::class, 'organization_id', 'site_id');
}
```

doesn't do/change anything. Larastan makes the return type `Relations\HasManyThrough<SiteCheck>` anyway. And then the generic is lost. And then `getQuery()` fails its own generic. Or something. I don't know Phpstan well enough.

**Comment by rudiedirkx** [comment] 2024-10-14 14:02
If I hack Larastan's `ModelRelationsDynamicMethodReturnTypeExtension` to skip `Organization::site_checks()` Phpstan will use the `@return`, and the first dumpType 'works':

    Relations\HasManyThrough<SiteCheck<*>>

But that still doesn't fix the `getQuery()` type:

    EloquentBuilder<EloquentModel>

It's still the base Model! Why doesn't it use `SiteCheck` or `SiteCheck<*>` ??

**Comment by calebdw** [comment] 2024-10-14 14:04
I'll take a look. Is that the only relation or does it do that for all relation types?

**Comment by rudiedirkx** [comment] 2024-10-14 14:22
Omg I'm an idiot. `Site` also has a relationship to `SiteCheck`, and it works perfectly there. The problem isn't that `SiteCheck` is a generic, but the `HasManyThrough` relationship! Another through-relationship somewhere else has the same problem:

```php
\PHPStan\dumpType($contact->sites()); // 🟩 Relations\HasManyThrough<Site>
\PHPStan\dumpType($contact->sites()->getQuery()); // 🟥 EloquentBuilder<EloquentModel>
```

`Site` is not a generic, but `sites()` is a `HasManyThrough`. **That** is the problem. I still don't know why, but that's progress 😆

**Comment by canvural** [comment] 2024-10-14 21:12
@rudiedirkx Could you try the latest `2.x` branch? It seems to be fixed cause I can't reproduce it.

**Comment by rudiedirkx** [comment] 2024-10-15 11:54
@canvural Your commit messages are inspirational 😆 

----

I'm getting a whole bunch new errors (was 0) on the 2.x branch, including this beauty:

    Method App\Models\ResponsibilityType::rolesQuery() should return Illuminate\Database\Eloquent\Builder<App\Models\ResponsibilityType> but returns Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<static(App\Models\ResponsibilityType)>>>>>>>>>>>>>>>>

Wooooooow what!? That method:

```php

/** @return Builder<self> */
static public function rolesQuery(?Organization $organization = null) : Builder {
	return self::query()
		->select(['responsibility_types.*'])
		->selectRaw('count(sr.id) as used')
		->leftJoin('site_responsibles as sr', function(JoinClause $join) {
			// more stuff here
		})
		->groupBy('responsibility_types.id');
}
```

And 10 more new errors, most complaining about `static(...)`.

----

But the `getQuery()` problem seems to be fixed 😮 

```php
\PHPStan\dumpType($organization->site_checks()); // 🟩 Relations\HasManyThrough<SiteCheck, Site, Organization>
\PHPStan\dumpType($organization->site_checks()->getQuery()); // 🟩 EloquentBuilder<SiteCheck>
```

With even more genericness in `HasManyThrough` than before, m'kay, but it passes to the Builder correctly 👍

**Comment by calebdw** [comment] 2024-10-15 12:33
The recursive generics would've been prevented by #1990

You can test with my fork: https://github.com/calebdw/larastan

**Comment by rudiedirkx** [comment] 2024-10-15 14:09
Will all the `static()` and `$this()` related errors be fixed before next release? Or are those real stan errors? We're getting off topic here, but I'd like to know if the next release breaks more than it fixes for me. For instance:

> Method User::choosable_organizations() should return Relations\BelongsToMany<Organization, User> but returns Relations\BelongsToMany<Organization, $this(User)>

Or did I define the relation wrongly (it reuses another relation method):

```php
public function organizations() : Relations\BelongsToMany {
	return $this->belongsToMany(Organization::class, 'users_organizations', 'user_id')
		->orderBy('organizations.name')
		->withPivot(['id', 'role', 'created_at', 'created_by'])
		->using(OrganizationUser::class);
}

/** @return Relations\BelongsToMany<Organization, self> */
public function choosable_organizations() : Relations\BelongsToMany {
	return $this->organizations()
		->where('organizations.status', '<>', OrganizationStatus::DISABLED);
}
```

Larastan/Phpstan was always okay with that, and now it's not (in `2.x`). Did Larastan get better or worse? 😆

**Comment by calebdw** [comment] 2024-10-15 14:10
The error is correct, this should be:

```php
/** @return Relations\BelongsToMany<Organization, $this> */
```

**Comment by rudiedirkx** [comment] 2024-10-15 14:13
Another one:

> Method Site::adminIndexQuery() should return EloquentBuilder<Site> but returns EloquentBuilder<static(Site)>.

What does that even mean? `static(Site)`? Isn't that fine? A `static(Site)` (does that mean a child class of `Site`??) is always a `Site`, isn't it? Why complain about it?

Even with this method stan complains:

```php
/** @return Builder<self> */
static public function adminIndexQuery(Request $request) : Builder {
	return self::query();
}
```

**Comment by calebdw** [comment] 2024-10-15 14:15
This should be:

```php
/** @return Builder<static> */
```

**Comment by rudiedirkx** [comment] 2024-10-15 14:17
> This should be:
> 
> ```
> /** @return Builder<static> */
> ```

Why? That's not true. I use `self` instead of `static` on purpose. This one gets no complaints:

```php
/** @return Builder<static> */
static public function adminIndexQuery(Request $request) : Builder {
	return static::query();
}
```

but that actually does something else. I don't want `static::query()`.

I probably just don't understand what Phpstan means by static, but PHP and I agree, Phpstan just doesn't.

**Comment by calebdw** [comment] 2024-10-15 14:20
> but that actually does something else. I don't want static::query().

No it doesn't---if you really want `self` then you need to make the model final. Calling `self::query()` actually does return a `Builder<static>` because the method calls `new static`. This is correct.

```php
/**
 * Begin querying the model.
 *
 * @return \Illuminate\Database\Eloquent\Builder<static>
 */
public static function query()
{
    return (new static)->newQuery();
}
```

**Comment by rudiedirkx** [comment] 2024-10-15 14:24
The original static is remembered through static calls into `query()`?? Okay, maybe I don't know how PHP works after all 😆 But then Phpstan should complain about the unsafe `new static()` calls, right? That's why I usually use `self` instead of `static`. You never know what class `static` is gonna be.

**Comment by calebdw** [comment] 2024-10-15 14:25
> But then Phpstan should complain about the unsafe new static() calls, right?

It would if you were analyzing the framework---but you're not. Calling `static::query()` is not going to generate complaints about `new static()`

**Comment by rudiedirkx** [comment] 2024-10-15 14:31
And somehow we accept that? As long as Phpstan passes 😢 Even though the framework wouldn't pass. That seems weird. How can you have a stan validated project built on top of a non-validated framework?

Thanks for all the patience @calebdw

**Comment by calebdw** [comment] 2024-10-15 14:32
> How can you have a stan validated project built on top of a non-validated framework?


That happens all the time, which is why you don't analyze the `vendor` directory

**Comment by canvural** [comment] 2024-10-15 19:46
@rudiedirkx I made some adjustments. Can you try the latest 2.x branch again? I'll also test it more later.

**Comment by rudiedirkx** [comment] 2024-10-15 20:08
All fixable errors now 👍

No code changes, just annotations, that's a lot of meta-coding. We need native generics! There's no way to do those wrong. Maybe? 😆 Thanks again guys! ❤️

**Comment by canvural** [comment] 2024-10-15 20:46
Good to hear. It doesn't work correctly for self:: case, I'll look at that later.

Can we close this?

**Comment by calebdw** [comment] 2024-10-15 20:48
> Good to hear. It doesn't work correctly for self:: case, I'll look at that later.

It doesn't need to, as I mention earlier `self::query()`, `self::create()`, etc. should return `static` *because that's what really happens*

**Comment by rudiedirkx** [comment] 2024-10-16 13:23
> Can we close this?

Good enough for me.

In the meantime I've found more bugs of course ;)

**Closed as completed** 2024-11-02 16:31 UTC
Labels: bug
