### ISSUE TITLE
Call to an undefined static method Illuminate\Support\Facades\Redis::{get,set}().

### ISSUE THREAD

**Issue by williamdes** [nunomaduro/larastan#1078] opened 2022-01-05 12:53 UTC
- Larastan Version: 8.77
- `--level` used: max

### Description

https://github.com/phpstan/phpstan/issues/6300#issuecomment-1005633454

Ref: https://github.com/phpstan/phpstan/issues/6300

### Laravel code where the issue was found

```php
<?php

namespace App\Transformers;

use Illuminate\Support\Facades\Redis;

class AddressTransformer
{

    public function getPostalCodeAndCity($lat, $lng)
    {
        $redisKey = 'foo';
        if (empty(Redis::get($redisKey))) {
            Redis::set($redisKey, $res);
        } else {
            return Redis::get($redisKey);
        }
    }
}
```

**Comment by szepeviktor** [comment] 2022-01-05 14:05
Hello William!

I think Larastan is not PHPStan v1.3 compatible.

**Comment by williamdes** [comment] 2022-01-05 14:46
> Hello William!
> 
> I think Larastan is not PHPStan v1.3 compatible.

Hello !

thanks for letting me know about it, nothing important except the undefined methods did pop out in our baseline

**Comment by rogatty** [comment] 2022-03-10 08:06
This is still an issue in Larastan v1.0.3 and PHPStan v1.4.8. Can't verify Larastan v2 because we're still on Laravel v8.

**Comment by ambengers** [comment] 2022-08-01 00:53
It's still an issue in Larastan 2.1.11 (PHPStan 1.7.15) with Laravel Framework 9.18.

Error: `Call to an undefined static method Illuminate\Support\Facades\Mail::getSymfonyTransport()`

Affected code:

```
use Illuminate\Support\Facades\Mail;

$transport = Mail::getSymfonyTransport();
```

I believe the issue is since the method is not defined within the facade class itself, but on the service the facade class is pointing at, PHPStan is not able to parse it properly.

We'll just be marking the affected line as ignored for now.

**Comment by canvural** [comment] 2023-01-10 09:12
This seems to be fixed in last versions.

**Closed by canvural** 2023-01-10 09:12 UTC

**Comment by cyppe** [comment] 2025-03-17 16:56
Static method Redis::pipeline() invoked with 1 parameter, 0 required.

Also problem here.

For syntax mentioned in docs as example:

```
Facades\Redis::pipeline(function (Redis $pipe) {
    for ($i = 0; $i < 1000; $i++) {
        $pipe->set("key:$i", $i);
    }
});
````

Had to add to ignore errors for now.
