### ISSUE TITLE
EntryNotFoundException 

### ISSUE THREAD

**Issue by terryShifft** [nunomaduro/larastan#105] opened 2018-08-01 13:56 UTC
- Larastan Version: 0.2.4
- `--level` used:0

### Description:
Summary of a problem or a feature request
While running code:analyse on level 0 I got an error, the stacktrace as found in the log is:
[2018-08-01 15:27:53] local.ERROR: {"exception":"[object] (Illuminate\Container\EntryNotFoundException(code: 0): at /home/html/hezelaer/smart/application/dev_terry/vendor/laravel/framework/src/Illuminate/Container/Container.php:613)
[stacktrace]
```#0 /home/html/hezelaer/smart/application/dev_terry/vendor/nunomaduro/larastan/src/Concerns/HasContainer.php(64): Illuminate\Container\Container->get('App\\Interfaces\\...')
#1 /home/html/hezelaer/smart/application/dev_terry/vendor/nunomaduro/larastan/src/Properties/Extension.php(42): NunoMaduro\Larastan\Properties\Extension->resolve('App\\Interfaces\\...')
#2 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Reflection/ClassReflection.php(186): NunoMaduro\Larastan\Properties\Extension->hasProperty(Object(PHPStan\Reflection\ClassReflection), 'name')
#3 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Type/ObjectType.php(48): PHPStan\Reflection\ClassReflection->hasProperty('name')
#4 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/Scope.php(1330): PHPStan\Type\ObjectType->hasProperty('name')
#5 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/Scope.php(352): PHPStan\Analyser\Scope->resolveType(Object(PhpParser\Node\Expr\PropertyFetch))
#6 /home/html/hezelaer/smart/application/dev_terry/vendor/nunomaduro/larastan/src/Analyser/Scope.php(46): PHPStan\Analyser\Scope->getType(Object(PhpParser\Node\Expr\PropertyFetch))
#7 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/Scope.php(611): NunoMaduro\Larastan\Analyser\Scope->getType(Object(PhpParser\Node\Expr\PropertyFetch))
#8 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/Scope.php(352): PHPStan\Analyser\Scope->resolveType(Object(PhpParser\Node\Expr\BinaryOp\Concat))
#9 /home/html/hezelaer/smart/application/dev_terry/vendor/nunomaduro/larastan/src/Analyser/Scope.php(46): PHPStan\Analyser\Scope->getType(Object(PhpParser\Node\Expr\BinaryOp\Concat))
#10 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/Scope.php(610): NunoMaduro\Larastan\Analyser\Scope->getType(Object(PhpParser\Node\Expr\BinaryOp\Concat))
#11 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/Scope.php(352): PHPStan\Analyser\Scope->resolveType(Object(PhpParser\Node\Expr\BinaryOp\Concat))
#12 /home/html/hezelaer/smart/application/dev_terry/vendor/nunomaduro/larastan/src/Analyser/Scope.php(46): PHPStan\Analyser\Scope->getType(Object(PhpParser\Node\Expr\BinaryOp\Concat))
#13 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/Scope.php(611): NunoMaduro\Larastan\Analyser\Scope->getType(Object(PhpParser\Node\Expr\BinaryOp\Concat))
#14 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/Scope.php(352): PHPStan\Analyser\Scope->resolveType(Object(PhpParser\Node\Expr\AssignOp\Concat))
#15 /home/html/hezelaer/smart/application/dev_terry/vendor/nunomaduro/larastan/src/Analyser/Scope.php(46): PHPStan\Analyser\Scope->getType(Object(PhpParser\Node\Expr\AssignOp\Concat))
#16 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(1430): NunoMaduro\Larastan\Analyser\Scope->getType(Object(PhpParser\Node\Expr\AssignOp\Concat))
#17 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(1396): PHPStan\Analyser\NodeScopeResolver->updateScopeForVariableAssign(Object(NunoMaduro\Larastan\Analyser\Scope), Object(PhpParser\Node\Expr\AssignOp\Concat), Object(PHPStan\TrinaryLogic), Object(PHPStan\Analyser\LookForAssignsSettings))
#18 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(1609): PHPStan\Analyser\NodeScopeResolver->lookForAssigns(Object(NunoMaduro\Larastan\Analyser\Scope), Object(PhpParser\Node\Expr\AssignOp\Concat), Object(PHPStan\TrinaryLogic), Object(PHPStan\Analyser\LookForAssignsSettings))
#19 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(1018): PHPStan\Analyser\NodeScopeResolver->lookForAssignsInBranches(Object(NunoMaduro\Larastan\Analyser\Scope), Array, Object(PHPStan\Analyser\LookForAssignsSettings))
#20 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(202): PHPStan\Analyser\NodeScopeResolver->lookForAssigns(Object(NunoMaduro\Larastan\Analyser\Scope), Object(PhpParser\Node\Stmt\If_), Object(PHPStan\TrinaryLogic), Object(PHPStan\Analyser\LookForAssignsSettings))
#21 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(574): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
#22 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(193): PHPStan\Analyser\NodeScopeResolver->processNode(Object(PhpParser\Node\Stmt\If_), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
#23 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(790): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure), NULL)
#24 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(193): PHPStan\Analyser\NodeScopeResolver->processNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
#25 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(790): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure), NULL)
#26 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(193): PHPStan\Analyser\NodeScopeResolver->processNode(Object(PhpParser\Node\Stmt\Class_), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
#27 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(790): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure), NULL)
#28 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(193): PHPStan\Analyser\NodeScopeResolver->processNode(Object(PhpParser\Node\Stmt\Namespace_), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
#29 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Analyser/Analyser.php(132): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
#30 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Command/AnalyseApplication.php(131): PHPStan\Analyser\Analyser->analyse(Array, false, Object(Closure), NULL, true)
#31 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/src/Command/AnalyseCommand.php(239): PHPStan\Command\AnalyseApplication->analyse(Array, Object(PHPStan\Command\ErrorsConsoleStyle), Object(PHPStan\Command\ErrorFormatter\TableErrorFormatter), false, true)
#32 /home/html/hezelaer/smart/application/dev_terry/vendor/symfony/console/Command/Command.php(251): PHPStan\Command\AnalyseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /home/html/hezelaer/smart/application/dev_terry/vendor/symfony/console/Application.php(886): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /home/html/hezelaer/smart/application/dev_terry/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /home/html/hezelaer/smart/application/dev_terry/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /home/html/hezelaer/smart/application/dev_terry/vendor/phpstan/phpstan/bin/phpstan(39): Symfony\Component\Console\Application->run()
#37 {main}
"}```

**Comment by szepeviktor** [comment] 2018-08-05 15:43
```
Could you use triple backticks ``` around the output?
```

**Comment by terryShifft** [comment] 2018-08-06 07:16
I've added the backticks

**Comment by szepeviktor** [comment] 2018-08-06 08:14
Thanks.

**Comment by szepeviktor** [comment] 2018-08-06 08:18
Could be a duplicate of #107

**Comment by nunomaduro** [comment] 2018-09-01 19:53
This issue should be fixed, can you guys make a quick test?

**Closed** 2018-09-02 21:39 UTC

**Comment by hartman** [comment] 2018-09-04 06:49
I had this problem too, and it seems to be fixed for me. Great work !
