### ISSUE TITLE
PHPStan 1.12.1 reports incorrect return value from EloquentBuilder calls that are forwarded to QueryBuilder

### ISSUE THREAD

**Issue by nxu** [nunomaduro/larastan#2032] opened 2024-09-04 08:23 UTC
- PHPStan Version: 1.12.1
- Larastan Version: v2.9.8
- Laravel Version: v11.22.0

I understand this is not a bug by Larastan, but rather a Laravel-specific PHPStan issue.

### Description
PhpStan 1.12.1 has released and includes a change that checks @mixin PHPDoc tags. The Eloquent Builder class (`Illuminate\Database\Eloquent\Builder`) uses `@mixin \Illuminate\Database\Query\Builder` to indicate the forwarded calls.

The problem is that the query builder methods return `$this`, and even though the `__call()` by the Eloquent Builder ignores it, PhpStan now reads this using the @mixin and thinks that these methods change the builder instance to the Query builder one.

### Laravel code where the issue was found

```php
use Illuminate\Database\Eloquent\Builder;

function (Builder $query, string $search): Builder {
    $lower = mb_strtolower($search);

    return $query
        ->where('email', 'like', "%{$search}%")
        ->orWhereRaw("LOWER(billing_address->'$.name') LIKE ?", ["%$lower%"]);
}
```

PHPStan report:

```
Anonymous function should return Illuminate\Database\Eloquent\Builder but returns Illuminate\Database\Query\Builder.
```

**Comment by calebdw** [comment] 2024-09-04 10:38
Thanks for this report, I'll dig into this

**Comment by calebdw** [comment] 2024-09-04 11:13
I believe this relates to https://github.com/phpstan/phpstan/issues/11342. We are currently using MethodClassReflection extensions for all the model / builder forwarding, however, the `@mixin` tag is essentially the same extension and therefore the custom extension is not used when the `@mixin` tag exists.

Ondres thinks we should be using the DynamicReturnType extensions instead

**Comment by korridor** [comment] 2024-09-05 12:16
If someone needs a temporary solution, fixing the version of `phpstan/phpstan` to `1.12.0` solved it for me. (https://github.com/solidtime-io/solidtime/pull/140/commits/588c810b6a8501df95f1e7c352e712fe918d22dd)

**Comment by ondrejmirtes** [comment] 2024-09-05 12:31
Fixed in PHPStan: https://github.com/phpstan/phpstan-src/commit/c889baa9ec60394e9201b2a7054486c66b40fa9b

Can you please verify this works for you by installing `phpstan/phpstan:^1.12.2`? It will install a current dev version.

I'd also like a regression test to be added here in Larastan to make sure PHPStan doesn't break this in the future: https://github.com/phpstan/phpstan/issues/11342#issuecomment-2331400649

**Comment by korridor** [comment] 2024-09-05 12:37
@ondrejmirtes Just tried it with `1.12.2` locally and that also works for me. Thanks :)

**Comment by ondrejmirtes** [comment] 2024-09-05 16:12
Fix is released: https://github.com/phpstan/phpstan/releases/tag/1.12.2

**Comment by canvural** [comment] 2024-09-27 16:37
Looks like this can be closed. Thank you everyone involved 👍🏽

**Closed as completed by canvural** 2024-09-27 16:37 UTC
Labels: bug
