### ISSUE TITLE
Literal string is not a `non-empty-string`

### ISSUE THREAD

**Issue by lloricode** [nunomaduro/larastan#1009] opened 2021-11-05 03:54 UTC
- Larastan Version: 1.0.0
- `--level` used: 7
- Pull request with failing test:

### Description

non-empty-string appeared as errors even no actually bugs happen

### Laravel code where the issue was found

```php

#  381
        $products = Product::whereIn((new Product())->getRouteKeyName(), $values)
            ->pluck('title', (new Product())->getRouteKeyName())
            ->toArray();

# 417
        $users = User::whereIn((new User())->getRouteKeyName(), $values)
            ->get()
            ->pluck('full_name', (new User())->getRouteKeyName())
            ->toArray();

# 610
       $products = Product::whereIn((new Product())->getRouteKeyName(), $this->freeProducts)->get();

# 627
       ? User::whereIn(
                (new User())->getRouteKeyName(),
                $this->specificCustomers
            )->get()->all()
            : [];

# models
    public function getRouteKeyName(): string
    {
        return 'slug';
    }
```
![Screenshot from 2021-11-05 11-44-09](https://user-images.githubusercontent.com/8251344/140454865-431d1d4d-ac7b-49b1-8a69-582d0e03850a.png)

I try to search the solution but it was not found any

thank you

**Comment by szepeviktor** [comment] 2021-11-05 06:46
Welcome back Lloric! 👋 
This is _ask question get help_ :)

```php
    /**
     * @phpstan-return non-empty-string
     */
    public function getRouteKeyName(): string
    {
        return 'slug';
    }
```

@canvural Why is a literal string not a `non-empty-string`?

**Comment by nunomaduro** [comment] 2021-11-05 07:40
cc @canvural This is the issue we have discussed.

**Comment by lloricode** [comment] 2021-11-05 08:06
> cc @canvural This is the issue we have discussed.

thanks @nunomaduro , my anxiety gone 😅

**Comment by lloricode** [comment] 2021-11-05 08:09
> Welcome back Lloric! 👋 
> This is _ask question get help_ :)
> 
> ```php
>     /**
>      * @phpstan-return non-empty-string
>      */
>     public function getRouteKeyName(): string
>     {
>         return 'slug';
>     }
> ```
> 
> @canvural Why is a literal string not a `non-empty-string`?

yes exactly

**Comment by lloricode** [comment] 2021-11-05 08:10
> Welcome back Lloric! 👋 
> This is _ask question get help_ :)
> 
> ```php
>     /**
>      * @phpstan-return non-empty-string
>      */
>     public function getRouteKeyName(): string
>     {
>         return 'slug';
>     }
> ```
> 
> @canvural Why is a literal string not a `non-empty-string`?

never try that, will try that on next weekday

**Comment by JonasPardon** [comment] 2021-11-05 10:49
Running into this as well, seems to be fixed in https://github.com/phpstan/phpstan-src/commit/1283db7ae426142af99b41a480c964fb8a2c8c83

**Comment by canvural** [comment] 2021-11-05 13:47
Hi,

The issue is because `getRouteKeyName` has return type hint `string` but `whereIn` expects `non-empty-string` It is not about literal strings.

> even no actually bugs happen

A bug can happen. It's highly unlikely but `getRouteKeyName` can return empty string (`''`) for some reason. This is here to prevent that.

We can solve it by also stubbing the `getRouteKeyName` but now I also think the benefits are not that much.

@nunomaduro We can revert that commit I think.

**Comment by lloricode** [comment] 2021-11-05 14:20
> Hi,
> 
> The issue is because `getRouteKeyName` has return type hint `string` but `whereIn` expects `non-empty-string` It is not about literal strings.
> 
> > even no actually bugs happen
> 
> A bug can happen. It's highly unlikely but `getRouteKeyName` can return empty string (`''`) for some reason. This is here to prevent that.
> 
> We can solve it by also stubbing the `getRouteKeyName` but now I also think the benefits are not that much.
> 
> @nunomaduro We can revert that commit I think.

I see, this make sense now

**Comment by lloricode** [comment] 2021-11-05 15:19
> Hi,
> 
> The issue is because `getRouteKeyName` has return type hint `string` but `whereIn` expects `non-empty-string` It is not about literal strings.
> 
> > even no actually bugs happen
> 
> A bug can happen. It's highly unlikely but `getRouteKeyName` can return empty string (`''`) for some reason. This is here to prevent that.
> 
> We can solve it by also stubbing the `getRouteKeyName` but now I also think the benefits are not that much.
> 
> @nunomaduro We can revert that commit I think.

this is work now, but there is another

```php
      fn(Builder $query, string $direction) => $query
          ->orderBy(
/* 45 */  VariantType::select('title')
                  ->orWhereColumn(
                      $this->repository->makeModel()->getTable().'.variant_type_id',
                      (new VariantType())->getTable().'.'.(new VariantType())->getKeyName(),
                  ),
/* 50  */    $direction
          )
```
![Screenshot from 2021-11-05 23-17-27](https://user-images.githubusercontent.com/8251344/140534346-5f166a28-c0b9-430d-9a0f-97ab27f16431.png)


i dont know how to type hint this

**Comment by szepeviktor** [comment] 2021-11-05 15:46
Maybe PHPStan supports Docblocks for closures.

```php
/**
 * @param non-empty-string $direction
 */
fn(Builder $query, string $direction) => $query
```

**Comment by szepeviktor** [comment] 2021-11-05 15:49
No :( https://github.com/phpstan/phpstan/issues/3770#issuecomment-793564311
You can do it inside the closure
```php
/** @var non-empty-string $direction */
```

**Comment by lloricode** [comment] 2021-11-05 15:58
> No :( [phpstan/phpstan#3770 (comment)](https://github.com/phpstan/phpstan/issues/3770#issuecomment-793564311) You can do it inside the closure
> 
> ```
> /** @var non-empty-string $direction */
> ```

Hi this is not working, even this 
```php
    /** @phpstan-var non-empty-string $direction */
```

**Comment by szepeviktor** [comment] 2021-11-05 16:08
Try normal closure definition: `function ($args) { ... }`

**Comment by LastDragon-ru** [comment] 2021-11-06 08:20
Some of setters accepts only a `non-empty-string` since 1.0, but getters still return `string` => so there are a lot of "expects non-empty-string, string given" :(

Moreover, I'm not sure how to solve:

```php
// class TestObject extends Model
$key = (new TestObject())->getKeyName();
$all = TestObject::query()->reorder($key)->get()->all();
```

that gives:
```
 31     Parameter #1 $column of method Illuminate\Database\Eloquent\Builder<LastDragon_ru\LaraASP\Eloquent\Testing\Package\Models\TestObject>::reorder() expects non-empty-string|null, string given.
```

In the theory `getKeyName()` can return an empty string, but adding a check on every usage looks too boring. 

Maybe there is another way? (except baseline)

**Comment by szepeviktor** [comment] 2021-11-06 08:36
You can add a stub to your project like this one https://github.com/nunomaduro/larastan/blob/master/stubs/EloquentBuilder.stub

**Comment by LastDragon-ru** [comment] 2021-11-06 10:34
@szepeviktor thanks, I'm trying to add it, but seems existing stubs removing when I add my own :( 

For example this stub
```
<?php declare(strict_types = 1);

namespace Illuminate\Database\Query;

class Builder {
    // empty
}
```

will remove all `non-empty-string` errors related to Query Builder...

**Comment by szepeviktor** [comment] 2021-11-06 11:33
Then copy the stubs file from Larastan, edit, then add it your project.

**Comment by LastDragon-ru** [comment] 2021-11-06 11:55
> Then copy the stubs file from Larastan, edit, then add it to your project.

And then track each new release of larastan? It definitely must not work like this.

**Comment by LastDragon-ru** [comment] 2021-11-06 12:04
I've added a question in phpstan repo - https://github.com/phpstan/phpstan/discussions/5945

**Comment by canvural** [comment] 2021-11-06 12:21
The commit that causes this issues will be reverted. We can close this issue. Sorry for the trouble.

**Closed by canvural** 2021-11-06 12:21 UTC

**Comment by LastDragon-ru** [comment] 2021-11-06 12:43
> Sorry for the trouble.

@canvural, no worries :) Actually, I probably will say 👍 about adding `non-empty-string`. But it needs some work, from my today's experience:

1) `Builder::qualifyColumn()` - new stub with `@return non-empty-string` needed (as I see this method cannot return empty string).
2) `Model:getKeyName()` - probably all fine and it can return empty string => code should be updated (this is fine for new major version).
3) Mixins and Closures - has some edge cases;

**Comment by LastDragon-ru** [comment] 2021-11-06 12:49
> Model:getKeyName() - probably all fine

From the docs https://laravel.com/docs/8.x/eloquent#primary-keys 

> Eloquent will also assume that each model's corresponding database table has a primary key

Code also expects PK, so probably `@return non-empty-string` can be added.

**Comment by szepeviktor** [comment] 2021-11-06 13:23
> Code also expects PK, so probably `@return non-empty-string` can be added.

PHPStan will alert if you accidentally set an empty string https://phpstan.org/r/3ef8d187-62e2-43c0-854d-ef0432260bd0

**Comment by canvural** [comment] 2021-11-06 21:06
Fix released in: https://github.com/nunomaduro/larastan/releases/tag/1.0.1

**Comment by lloricode** [comment] 2021-11-07 23:44
Thanks guys

**Comment by mfn** [comment] 2021-11-08 20:47
I'm on 1.0.1 but still I've a few places where I dynamically create the column name for those where conditions:
```php
…
->where('mode.' . $dynamicallyDerivedColumn)
```
On all those places I get now:
`Parameter #1 $column of method Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>::where() expects array<int|string, mixed>|Closure|Illuminate\Database\Query\Expression|string, non-empty-string given.`

In the cases I checked in my codebase, those names get passed it from other method calls and sometimes a) originate literally in the method call or b) reference constants.

I read through all comments here but unsure what the proposed fix here is. Should I open a new one?

Thank you!

**Comment by szepeviktor** [comment] 2021-11-08 20:52
We reverted `non-empty-string` from the stubs. 

I wonder why a `non-empty-string` value may not suffice a `string`!

**Comment by canvural** [comment] 2021-11-08 20:59
@mfn That doesn't look anything specific to Larastan. Try to reproduce it on phpstan.org maybe.
