### ISSUE TITLE
Relation is not found in pivot model.

### ISSUE THREAD

**Issue by ManuelLeiner** [nunomaduro/larastan#1312] opened 2022-07-20 10:39 UTC
- Larastan Version: 2.1.12
- `--level` used: 0
- Repo with example: https://github.com/ManuelLeiner/larastan-level-0

### Description
In the repo above you will find a basic Laravel Jetstream installation which reports a level 0 error. You can find a short summary below. What do you think of this error? Can I help in any other way?

#### Scenario
When using a pivot model class `TeamUser` in the `Team`'s `users()` relation, `phpstan analyse` reports a missing relation `projects()` which is of course implemented in the `User` model. 

```bash
/var/www/html# ./vendor/bin/phpstan analyse
Note: Using configuration file /var/www/html/phpstan.neon.
 39/39 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ----------------------------------------------------------------
  Line   Models/Project.php                                     
 ------ ----------------------------------------------------------------
  42     Relation 'projects' is not found in App\Models\TeamUser model.
 ------ ----------------------------------------------------------------

                                                                                                                        
 [ERROR] Found 1 error
 ```

#### App\Models\Team.php

```php
    /**
     * Get all of the users that belong to the team.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany(Jetstream::userModel(), Jetstream::membershipModel())
            ->withPivot('role')
            ->withTimestamps()
            ->as('membership')
            ->using(TeamUser::class);         <---- here is the custom pivot model
    }
```

#### App\Models\Project.php

```php
    /**
     * Get the team that owns the project.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function team()
    {
        return $this->belongsTo(Team::class);
    }

    /**
     * Returns a collection of all team members that are
     * not yet member of this project.
     *
     * @return \Illuminate\Support\Collection
     */
    public function getAvailableUsers(): Collection
    {
        return $this->team
            ->users()                                                // query all team members (team owner not included)
            ->where('user_id', '!=', $this->user_id)                 // exclude the current project's owner
            ->whereDoesntHave(                                       // exclude all current project members
                'projects',        <---- this is the relation being found by larastan/phpstan
                fn (Builder $query) => $query->where('projects.id', $this->id)
            )
            ->dd()        <---- see query below
            ->get()
            // do some other stuff with the collection
            ->sortBy('name')
            ->values();
    }
```

#### App\Models\User.php

```php
    /**
     * Get all of the projects the user belongs to.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function projects(): Relation
    {
        return $this->belongsToMany(Project::class)
            ->withPivot('role')
            ->withTimestamps()
            ->as('membership');
    }
```

#### Query

```sql
select * from "users"
inner join "team_user"
on "users"."id" = "team_user"."user_id"
where "team_user"."team_id" = ?
and "user_id" != ?
and not exists (
    select * from "projects"
    inner join "project_user"
    on "projects"."id" = "project_user"."project_id"
    where "users"."id" = "project_user"."user_id"
    and "projects"."id" = ?
)
```

**Comment by szepeviktor** [comment] 2022-07-20 11:43
Thank you Manuel!

`->as('membership')` is not understood.

Duplicate of #1308

**Closed by szepeviktor** 2022-07-20 11:43 UTC

**Comment by szepeviktor** [comment] 2022-07-20 11:46
@ManuelLeiner Have you tried adding PHP generics?

https://github.com/nunomaduro/larastan/blob/65cfc54fa195e509c2e2be119761552017d22a56/stubs/BelongsToMany.stub#L5-L9

```php
    /**
     * Get all of the projects the user belongs to.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany<\App\Models\Project>
     */
    public function projects(): Relation
```

**Comment by ManuelLeiner** [comment] 2022-07-20 17:43
> Thank you Manuel!
> 
> 
> 
> `->as('membership')` is not understood.
> 
> 
> 
> Duplicate of #1308 

I can confirm that removing the `->as()` gets rid of the error.

In production however we do not use the exact code as in the example above. We do not copy the code of the Jetstream Team into our Team model but we call the parent:

```php
    /**
     * Get all of the users that belong to the team.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return parent::user()->using(TeamUser::class);
    }
```

Even if I remove the `->as()` in the parent class the error stays. So there might as well be a problem with using the parent's method and chaining additional stuff. 


I will double check tomorrow.

**Comment by ManuelLeiner** [comment] 2022-07-21 09:00
As stupid as it sounds, the examples above behave strange. Sometimes the error occurs and sometimes not. Of course I changed a few lines here and there. The problem doesn't seem to be related to the `->as('membership')`.

I couldn't reproduce the error with the example of my entry post

#### App\Models\Team.php

```php
class Team extends JetstreamTeam 
{

    ...

    /**
     * Get all of the users that belong to the team.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany(Jetstream::userModel(), Jetstream::membershipModel())
            ->withPivot('role')
            ->withTimestamps()
            ->as('membership')
            ->using(TeamUser::class); 
    }
```

But I can reproduce the problem with the second example using `parent`, which I pushed to the repo mentioned in the entry post.

```php
class Team extends JetstreamTeam 
{

    ...

    /**
     * Get all of the users that belong to the team.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return parent::users()->using(TeamUser::class); 
    }
```

**Comment by szepeviktor** [comment] 2022-07-21 09:09
TBH I'm confused. Could you please open a new issue with only things related to this new error?

**Comment by zoe-edwards** [comment] 2023-01-31 12:44
If someone else finds this error, I actually just had a mistake and maybe you did the same thing:

I had used

    @return Illuminate\Database\Eloquent\Relations\BelongsTo

instead of

    @return \Illuminate\Database\Eloquent\Relations\BelongsTo
