### ISSUE TITLE
Internal error: Call to a member function connection() on null

### ISSUE THREAD

**Issue by ArtyomNorin** [nunomaduro/larastan#487] opened 2020-03-11 14:34 UTC
- Larastan Version: 0.5.2
- `--level` used: 7

### Description

Hi. I got the error from phpstan:
`Internal error: Call to a member function connection() on null`.

phpstan with --debug options give me that:

> In Model.php line 1255:
>                                                   
>   Call to a member function connection() on null 

So i think phpstan could not resolve static variable here https://github.com/illuminate/database/blob/6.x/Eloquent/Model.php#L1255
when i try save my models.

### Laravel code where the issue was found

```php
public static function resolveConnection($connection = null)
    {
        return static::$resolver->connection($connection);
    }
```
Thank you!

**Comment by canvural** [comment] 2020-03-11 14:39
Hi,

Thank you for reporting this.

Can you try to narrow down to a specific code where this error happens?

**Comment by ArtyomNorin** [comment] 2020-03-11 14:42
Yes, sure.

> DB::connection()->getPdo()->query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');

**Comment by canvural** [comment] 2020-03-11 14:52
So it gives the error while scanning that code? But there is no model used in the above code you gave. But the error is related to Model class.

**Comment by ArtyomNorin** [comment] 2020-03-11 14:56
Oh sorry, not that code.

> $balance->amount += $amoun;
> $balance->save();

**Comment by canvural** [comment] 2020-03-11 18:42
I'm not able to reproduce this. So if you can give more info about this it'd be helpful. And maybe you can try to delete some code until this error does not happen. So we can pinpoint where exactly its happening.

**Comment by ArtyomNorin** [comment] 2020-03-12 06:36
I have localized the problem.
I have the class Partner.
```
class Partner extends Model
{
    /**
     * @return HasMany
     */
    public function balances(): HasMany
    {
        return $this->hasMany(Balance::class);
    }
}
```
Then i do
```
$partner = Partner::find(1);

$partner->balances()->lockForUpdate()->where('currency', '=', 'USD')->first();
```
And after that i got the error.

**Comment by canvural** [comment] 2020-03-17 21:42
I am still not able to reproduce this. With the code you shared.

So, the only option is for you to debug this. Maybe try putting a breakpoint in `resolveConnection` method and check the call stack and see which Larastan code has executed that lead to that point.

**Comment by canvural** [comment] 2020-07-30 12:53
Closing this since we did not get any feedback. Feel free to open a new issue if the problem still occurs in the newer version of Larastan.

**Closed by canvural** 2020-07-30 12:53 UTC
Labels: Waiting for feedback

**Comment by kuberjsr** [comment] 2022-08-09 16:40
That issue is not reproducible as its occured becuase of local mistakes that dev like me always do and learn new things because of that. So basically you have to go in vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php and check for function named "resolveConnection", then you need to make dd for $resolver and it will give you exact error, like in my case I have remove one package but app.php has serviceProvider for that. I hope it will help others as well.
