### ISSUE TITLE
DB::raw in where clause

### ISSUE THREAD

**Issue by Firzenizer** [nunomaduro/larastan#1592] opened 2023-03-17 12:23 UTC
- Larastan Version: 2.5.1
- Laravel version: 10 (Lumen)
- `--level` used: 7

### Description
Example code of what I am doing. This is simplified version of my search.
```php
$query = Users::query();
$query->where(DB::raw('CONCAT(firstName, lastName)'), 'LIKE', "%Terry%");
```
This code works just fine, but I am getting following error and it makes no sense.
```
Parameter #1 $column of method Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>::where() expects array<int|string,
         mixed>|(Closure(Illuminate\Database\Eloquent\Builder): void)|(Closure(Illuminate\Database\Eloquent\Builder):
         Illuminate\Database\Eloquent\Builder)|Illuminate\Database\Query\Expression|string, Illuminate\Contracts\Database\Query\Expression given.
```

**Comment by szepeviktor** [comment] 2023-03-17 12:28
https://github.com/nunomaduro/larastan/blob/11bdd132565d37e808e4ac985a580b492c2d8887/stubs/EloquentBuilder.stub#L221

**Comment by szepeviktor** [comment] 2023-03-17 12:30
`where` accepts `\Illuminate\Database\Query\Expression`
`Illuminate\Contracts\Database\Query\Expression` given. That may be the problem.

**Comment by canvural** [comment] 2023-03-17 13:18
Duplicate of #1547

**Closed** 2023-03-17 13:18 UTC
