### ISSUE TITLE
Relationship description with soft deletion

### ISSUE THREAD

**Issue by sofianegargouri** [nunomaduro/larastan#2126] opened 2024-11-25 13:20 UTC
- Larastan Version: 3.0.0
- Laravel Version: 11.33.2

### Description

I can't find a way to describe my relationship when appending `withTrashed` to retrieve the related resource even when it's soft deleted. The error I'm getting is:

```sh
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
  Line   Models/Subscription.php                                                                                                                                                             
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
  :      Method App\Models\Subscription::company() should return Illuminate\Database\Eloquent\Relations\BelongsTo<App\Models\Company, $this(App\Models\Subscription)> but returns  
         Illuminate\Database\Eloquent\Relations\BelongsTo<App\Models\Company, Illuminate\Database\Eloquent\Relations\BelongsTo<App\Models\Company, $this(App\Models\Subscription)>>.         
         🪪  return.type                                                                                                                                                                     
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
```

### Laravel code where the issue was found

```php
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\Company, $this>
     */
    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class)->withTrashed();
    }

```

If I remove the `->withTrashed()` everything comes back to normal.

**Comment by calebdw** [comment] 2024-11-25 13:23
Duplicate of #2111 and fixed by #2119

**Closed as completed** 2024-11-26 23:07 UTC
Labels: bug
