### ISSUE TITLE
Incorrect EloquentBuilder stub param types for Expression

### ISSUE THREAD

**Issue by nie7321** [nunomaduro/larastan#1641] opened 2023-05-08 22:27 UTC
- Larastan Version: v2.6.0
- `--level` used: 5
- Pull request with failing test: [There is already a test](https://github.com/nunomaduro/larastan/blob/63326ddbfe83c395d339dd419b705de69f5d57f9/tests/Type/data/eloquent-builder.php#L379), but it's not failing and I am unclear why? I don't think it should be?

### Description
In a Laravel 10 app, for the below snippet, I am getting an error for the first parameter. I believe this is because the EloquentBuilder.stub has the concrete `Expression` listed, instead of the interface?

```
 160    Parameter #1 $column of method
         Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>::where() expects array<int|string,
         mixed>|(Closure(Illuminate\Database\Eloquent\Builder): void)|(Closure(Illuminate\Database\Eloquent\Builder):
         Illuminate\Database\Eloquent\Builder)|Illuminate\Database\Query\Expression|string,
         Illuminate\Contracts\Database\Query\Expression given.
```

`DB::raw()` should return `Illuminate\Contracts\Database\Query\Expression` [per the facade's type info](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Support/Facades/DB.php#LL55C60-L55C60).

The `Illuminate\Database\Eloquent\Builder::where()` should accept that, [according to its docblock](https://github.com/laravel/framework/blob/476f3b5eca57cd04401dd6f8b51283379cb34ce9/src/Illuminate/Database/Eloquent/Builder.php#L284). 

The above error from Larastan does not have the builder from the Contracts namespace listed though? That seems incorrect?

The stub file in Larastan lists the concrete implementation of the `Builder`, and not the interface in Contracts: https://github.com/nunomaduro/larastan/blob/63326ddbfe83c395d339dd419b705de69f5d57f9/stubs/EloquentBuilder.stub#L221

I think that should be corrected for `where`, `orWhere`, `orWhereRelation`, `firstWhere`, `value`, and `whereRelation`.

### Laravel code where the issue was found

```php
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\DB;

public function scopeFulltextSearch(Builder $query, string $term)
{
    return $query->where(DB::raw("first_name || ' ' || last_name"), 'ilike', $term);
}
```

**Comment by canvural** [comment] 2023-05-09 11:28
Hi,

This is a duplicate of this issue: https://github.com/nunomaduro/larastan/issues/1547

And [here](https://github.com/nunomaduro/larastan/issues/1547#issuecomment-1445468917) I wrote a short answer what the possible solution can be. Feel free to send a PR 👍🏽

**Closed by canvural** 2023-05-09 11:28 UTC
