### ISSUE TITLE
False positive when calling ->refresh() method on Model in a test

### ISSUE THREAD

**Issue by jdrieghe** [nunomaduro/larastan#806] opened 2021-04-09 06:45 UTC
- Larastan Version: 0.7.2
- `--level` used: max

### Description

The `->refresh()` method in a test started failing after updating to the latest Larastan version.

```php
$user = User::seed();
// operations which require a `$user` refresh
$context = Context::create()->withUser($user->refresh());
```

```
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
  Line   tests/Unit/Recommendations/ContextTest.php                                                                                                                                    
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
  40     Parameter #1 $user of method App\Domain\Recommendations\Context::withUser() expects App\Domain\Users\User, static(Tests\Unit\Recommendations\ContextTest) given.  
```

Note that `User::seed()` in this case is part of a trait that is implemented on the `User` model and returns `static`

### Laravel code where the issue was found

```php
    /**
     * Reload the current model instance with fresh attributes from the database.
     *
     * @return $this
     */
    public function refresh()
    {
    //...
    }
```

**Comment by canvural** [comment] 2021-04-09 07:31
Hi,

Can you add `\PHPStan\dumpType($user)` after `$user = User::seed();` part and tell me what is the output?

**Comment by jdrieghe** [comment] 2021-04-09 07:35
I dumped `$user` on line 40 en `$user->refresh()` on line 41

```
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   tests/Unit/Recommendations/ContextTest.php                                                                                                                                   
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  40     Dumped type: static(App\Domain\Users\User)                                                                                                                             
  41     Dumped type: $this(Tests\Unit\Recommendations\ContextTest)                                                                                                                   
  43     Parameter #1 $user of method App\Domain\Recommendations\Context::withUser() expects App\Domain\Users\User, $this(Tests\Unit\Recommendations\ContextTest) given.  
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
```

**Comment by szepeviktor** [comment] 2021-04-09 07:37
> en

For English readers: it means _and_

**Comment by canvural** [comment] 2021-04-11 18:20
I tried to reproduce this with the following

```php
$user = User::seed();
// operations which require a `$user` refresh
$context = Context::create()->withUser($user->refresh());

class User extends \Illuminate\Database\Eloquent\Model {
    use Seed;
}

class Context extends \Illuminate\Database\Eloquent\Model {
    public function withUser(User $user): Context
    {
        return $this;
    }
}

trait Seed {
    /** @return static */
    public static function seed() {
        $instance = new static;

        return $instance;
    }
}
```

and I don't get the error you get. Here is also similar thing: https://phpstan.org/r/6f7caf44-a99d-4840-9b23-2bc5ffe65469

Can you share the signature of the `seed` method? And how you instantiate the class in the trait?

**Comment by jdrieghe** [comment] 2021-04-12 06:04
Sorry, I should have provided that part from the start. The seed is essentially a wrapper around `HasFactory`:
```
    /**
     * @return static
     */
    public static function seed(array $attributes = []): self
    {
        return static::factory()->create($attributes);
    }
```

**Comment by canvural** [comment] 2021-04-12 08:39
So it's similar to the code I posted above. I moved the trait to another file and tried again, but still can't produce it.

Can you try to PR a failing test for this?

**Comment by canvural** [comment] 2021-06-14 06:37
Hi,

I'm gonna close this issue because there is no new activity in 2 months. If you can send a failing test case in a PR, I'd take a look 👍🏽

**Closed by canvural** 2021-06-14 06:37 UTC
