### ISSUE TITLE
Undefined property on models when using postgres schema

### ISSUE THREAD

**Issue by dododedodonl** [nunomaduro/larastan#1642] opened 2023-05-10 08:47 UTC
- Larastan Version: 2.6.0
- `--level` used: 5

### Description
In postgres, it is possible to use multiple schemas/search paths in a single database connection. In order to access some tables in a different schema then the default ones set in the laravel database config, they are prefixed to the table name in `getTable()` on the specific models (eg. `anotherSchema.tableName` instead of `tableName`).

It seems larastan cannot match the tablenames anymore to the migrations, and this results in undefined property errors when running phpstan.

**Comment by szepeviktor** [comment] 2023-05-10 08:50
> It seems larastan cannot match the tablenames anymore to the migrations

Yes. It is a missing feature.

**Comment by canvural** [comment] 2023-06-04 08:18
Seems like duplicate of #1577

**Closed by canvural** 2023-06-04 08:18 UTC

**Comment by dododedodonl** [comment] 2023-06-04 08:43
@canvural it is not a duplicate, as only 1 database connection is used. Postgres databases are split into schema’s (sub databases), which can be accessed by adding it in front of the table. Larastan is not correctly interpreting this, and accessing all tables from the main (public) schema in the database.

**Comment by calebdw** [comment] 2024-03-10 19:52
@dododedodonl,

As long as the Models are declaring the schema as part of the table name:

```php
class Invoice extends Model
{
    protected $table = 'accounting.invoices';
}
```

and migrations are using the schema:

```php
    {
        Schema::create('accounting.invoices', function (Blueprint $table) {
            $table->id();
            $table->string('invoice_number');
            $table->date('invoice_date');
            $table->timestamps();
        });
    }
```

then Larastan should work without an issue.

Is this still a problem? If so, then I'll need an mvp to troubleshoot. Are you using squashed migrations / schema dump or only reading the migrations?

**Comment by dododedodonl** [comment] 2024-03-11 11:00
Both the models and the migrations are specifying the schema. Only difference from your example I see is that I use the `getTable()` method to set the schema. I'll try to make a repo to reproduce the issue one of the coming days.

**Comment by calebdw** [comment] 2024-03-11 13:57
> Only difference from your example I see is that I use the getTable() method to set the schema. 

That shouldn't matter though because Larastan directly calls the model instance's `getTable` method
