### ISSUE TITLE
Invalid "self" type for custom Builder

### ISSUE THREAD

**Issue by spaceemotion** [nunomaduro/larastan#352] opened 2019-10-28 15:29 UTC
- Larastan Version: 0.4.3
- `--level` used: max

### Description
Based on https://timacdonald.me/dedicated-eloquent-model-query-builders/ I have converted most of my code base away from Model scopes to custom query builders. This made using them in an IDE a lot asier.

Problem is: Simple functions like
```php
public function whereActive(): self
{
  return $this->whereNotNull('accepted_at');
}
```
work as expected. The problem starts as soon as another "scope" gets called inside this builder:

### Laravel code where the issue was found
(just an example)

```php
class UserBuilder extends Builder {
  public function whereVerified(): self
  {
    return $this->whereNotNull('email_verified_at');
  }

  public function whereVip(): self
  {
    return $this->whereVerified()->where('points', '>', 50000);
  }
}
```

Since whereVerified() returns an instance of `self` this seems to overwrite the analysis and any consecute calls get the wrong scope. Even attaching PHPDocs like `@return \Illuminate\Database\Eloquent\Builder|self` don't work.

**Comment by spaceemotion** [comment] 2019-10-28 15:39
Btw, this also fails in the following case:

```php
User::query()->whereNotNull('email')->whereVip()->get();
```

says `whereVip` could not be found.

**Comment by canvural** [comment] 2019-10-28 20:00
So basically in this case `User::query` returns `UserBuilder`

Can you try adding `/** @method static UserBuilder query */` to your `User` model annotation?

**Comment by spaceemotion** [comment] 2019-10-28 20:41
That's what I already have.

**Comment by canvural** [comment] 2019-10-29 07:42
Can you write the exact error you are getting, with the line?

**Comment by spaceemotion** [comment] 2019-10-29 08:19
Hm, so after some further investigation it seems like this originates from a typehint issue in laravel itself:

```php
public function visibleForUser($user): self
{
  return $this->whereIn(.....);
}
```

fails, as the typehint for `whereNotIn` is `\Illuminate\Database\Query\Builder|static`, while `whereIn` simply returns `$this`. If I call whereIn directly, everything works.

Same for:
- `whereNotNull` (vs `whereNull`)
- 'joinSub`, `leftJoin`, and the rest of them (vs `join`)
- (other's I've probably missed)

**Comment by canvural** [comment] 2020-02-04 18:39
Hello,

Can you please test this with 0.5.1? We made some improvements to query builder and dynamic wheres. So it might be fixed.

**Comment by BertvanHoekelen** [comment] 2020-02-05 12:27
I can confirm that this isn't resolved in 0.5.1. I'm not really sure why because the return type in Laravel is the same for `where` as for `whereIn` but adding the following to [CustomEloquentBuilder](https://github.com/nunomaduro/larastan/blob/master/tests/Features/ReturnTypes/CustomEloquentBuilderTest.php#L76) results in `Method Tests\\Features\\ReturnTypes\\CustomBuilder::categories() should return Tests\\Features\\ReturnTypes\\CustomBuilder<TModelClass> but returns Illuminate\\Database\\Eloquent\\Builder.`

```php
/**
 * @param string[] $categories
 *
 * @return CustomBuilder
 * @phpstan-return CustomBuilder<TModelClass>
 */
public function categories(array $categories): CustomBuilder
{
    return $this->whereIn('category', $categories);
}
```

**Comment by canvural** [comment] 2020-02-05 13:10
@BertvanHoekelen I found the cause of the issue with your code example. `whereIn` is in `Query\Builder` and not in `Eloquent\Builder` and that causes some issues with the generic. I'll investigate further later.

**Comment by canvural** [comment] 2020-02-05 13:42
@BertvanHoekelen Is it possible for you to apply this [patch](https://gist.github.com/canvural/f3d35fd72106a1140ec302de6e20f752) and try again?

**Comment by BertvanHoekelen** [comment] 2020-02-05 13:45
Yep, give me a few minutes.

**Comment by BertvanHoekelen** [comment] 2020-02-05 14:02
Works like a charm @canvural  🎉

**Comment by canvural** [comment] 2020-02-05 14:02
Ok, great. I'll make a PR. I hope it also solves @spaceemotion's issue.

**Closed** 2020-02-05 15:05 UTC
Labels: bug, core-package

**Comment by spaceemotion** [comment] 2020-02-06 20:51
@canvural will have to see when I can test this. thanks for the work!
