### ISSUE TITLE
Custom queries prefixed with "where" get wrong type for first parameter

### ISSUE THREAD

**Issue by spaceemotion** [nunomaduro/larastan#353] opened 2019-10-28 15:35 UTC
- Larastan Version: 0.4.3
- `--level` used: max

### Description
Similar to #352 (based on custom query builders), I encountered the following Problem:
When I define custom methods that have `where` as their prefix, the first argument is getting the wrong parameter assigned during the analysis.

```
Parameter #1 $table (string|null) of method App\Builders\InvestorBuilder::whereHasActiveUser() should be compatible with parameter $parameters (array) of method Illuminate\Database\Query\Builder::whereHasActiveUser()
```

### Laravel code where the issue was found

```php
class InvestmentBuilder extends Builder
{
  use Traits\HasUser;

  public function withoutCommissions(): self
  {
    return $this->whereHasActiveUser('investors');
  }
}

trait HasUser
{
  public function whereHasActiveUser(?string $table = null): self
  {
    // ...
  }
}
```

**Comment by spaceemotion** [comment] 2019-10-28 15:43
Just noticed a related bug: if I call the following:

```php
Investment::query()->where('amount', '>', 1000)->whereHasActiveUser()
```

it gives me:

> Method Illuminate\Database\Query\Builder:: whereHasActiveUser() invoked with 0 parameters, 1 required.

**Comment by spaceemotion** [comment] 2019-11-25 15:08
Quick update, the following produces a related, but different error:

```php
    public function whereType(string $type): self
    {
        if (!in_array($type, Contract::TYPES)) {
            throw new InvalidArgumentException("Invalid contract type: {$type}");
        }

        return $this->where('type', $type);
    }
```

```
Parameter #1 $type (string) of method App\Builders\ContractBuilder::whereType() should be compatible with parameter $parameters (array) of method Illuminate\Database\Query\Builder::whereType()
```

**Comment by canvural** [comment] 2020-02-05 08:11
Hi,

Although I did not test specifically, this issue might be resolved in 0.5.1. Can you test again?

**Comment by mr-feek** [comment] 2020-02-20 00:49
I wasn't able to write a test case reproducing this, I believe it might be fixed now.

**Comment by spaceemotion** [comment] 2020-03-01 00:42
just FYI, I havent had the time to work on this yet since the updates came out. Will take a look at my issues tomorrow.

**Comment by canvural** [comment] 2020-04-12 15:45
As I said before, this should be fixed. I'm gonna close this issue because of the inactivity. Please open a new issue if you still have the same errors with the new versions. Thank you.

**Closed by canvural** 2020-04-12 15:45 UTC
Labels: Waiting for feedback
